site_name: Password Safe Documentation
site_author: MATESO GmbH
repo_url: https://github.com/BoxedBrain/pws-docs
repo_name: BoxedBrain/pws-docs

extra:
  generator: true
  social:
  - icon: fontawesome/brands/linkedin
    name: MATESO on LinkedIn
    link: https://www.linkedin.com/company/mateso-gmbh/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/matesogmbh

theme:
  logo: assets/logo_white.png
  favicon: assets/favicon.svg
  language: en
  name: material
  icon:
    repo: material/file-document-outline

  features:
  - navigation.indexes
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.instant
  - navigation.top
  - search.highlight
  - search.suggest
  - header.autohide
  - toc.autohide
  - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search:
      prebuild_index: true
  - git-revision-date-localized:
      enabled_if_env: CI
      type: date

markdown_extensions:
  - meta
  - abbr
  - admonition
  - footnotes
  - tables
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: ⚓︎
copyright: Maintained with ❤️ by <a href='https://www.passwordsafe.com' target='_blank'>MATESO GmbH</a> and <a href='/contributors'>contributors</a>

nav:
  - Welcome: index.md
  - Installation: 
    - installation/index.md
    - System requirements:
      - Server: installation/requirements/server.md
      - MSSQL: installation/requirements/mssql.md
      - Client: installation/requirements/client.md
      - Webserver: installation/requirements/webserver.md
    - Server: installation/server.md
    - Browser extensions:
      - installation/browser/chrome.md
      - installation/browser/edge.md
      - installation/browser/firefox.md
      - installation/browser/safari.md
    - Update: installation/update.md
  - FAQ:
    - Security:
      - faq/security/index.md
      - Made in Germany: faq/security/made_in_germany.md
      - Encryption: faq/security/encryption.md
      - Pentest: faq/security/pentest.md
