name: Enforce macro usage

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, review_requested]

  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  macrocheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check for "MATESO"
      run: bash grep --include=\*.{md,txt} --exclude={README.md,index.md,client.md,contributors.md} -rnw /mnt/c/git/pws-docs -e "MATESO"

    - name: Check for "Password Safe"
      run: bash grep --include=\*.{md,txt} --exclude={README.md,index.md,client.md} -rnw /mnt/c/git/pws-docs -e "Password Safe"