name: Enforce macro usage

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, review_requested]

  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  macrocheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show dir
        run: echo ${GITHUB_WORKSPACE} && ls -alh

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v25

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file
          done

      - name: Find String
        id: find-string
        uses: nguyenvanuyn96/str-find-action@master
        with:
          find: "MATESO"
          include: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: List all matches
        run: |
          echo "${{ steps.find-string.outputs.resultArray }} matching files found!"
          echo ${{ steps.find-string.outputs.resultArray }}

#      - name: Check for "MATESO"
#        run: grep --include=\*.{md,txt} --exclude={README.md,index.md,client.md,contributors.md} -rnw ${GITHUB_WORKSPACE} -e 'MATESO'
#
#      - name: Check for "Password Safe"
#        run: grep --include=\*.{md,txt} --exclude={README.md,index.md,client.md} -rnw ${GITHUB_WORKSPACE} -e 'Password Safe'