name: Check links with linkcheck

on:
  schedule:
    # Run every monday at 06:00 AM
    - cron: '0 6 * * 1'

  # Allow to run this workflow manually
  workflow_dispatch:

jobs:
  linkcheck:
    uses: filiph/linkcheck@v2.0.15+1
    with:
      arguments: https://docs.pwlab.de
